CREATE TABLE FT_SUPPLYORDER 
(
  受注計画番号 VARCHAR2(10 BYTE) 
, オーダ識別区分 VARCHAR2(1 BYTE) 
, 受注番号 VARCHAR2(10 BYTE) 
, 受注明細番号 VARCHAR2(3 BYTE) 
, 受注明細枝番 VARCHAR2(3 BYTE) 
, 売上ランク区分 VARCHAR2(3 BYTE) 
, 発注番号 VARCHAR2(10 BYTE) NOT NULL 
, 発注版数 VARCHAR2(3 BYTE) NOT NULL 
, 発注計画番号 VARCHAR2(10 BYTE) 
, 発注区分 VARCHAR2(3 BYTE) 
, 発注区分名 VARCHAR2(20 BYTE) 
, 本部コード VARCHAR2(3 BYTE) 
, 事業部コード VARCHAR2(3 BYTE) 
, 部コード VARCHAR2(3 BYTE) 
, グループコード VARCHAR2(3 BYTE) 
, 本部名 VARCHAR2(50 BYTE) 
, 事業部名 VARCHAR2(50 BYTE) 
, 部名 VARCHAR2(50 BYTE) 
, グループ名 VARCHAR2(50 BYTE) 
, 発注担当者コード VARCHAR2(10 BYTE) 
, 発注担当者名 VARCHAR2(50 BYTE) 
, 協力会社コード VARCHAR2(10 BYTE) 
, 協力会社名 VARCHAR2(50 BYTE) 
, 協力会社部署コード VARCHAR2(10 BYTE) 
, 協力会社部署名 VARCHAR2(50 BYTE) 
, ユーザコード VARCHAR2(10 BYTE) 
, ユーザ名 VARCHAR2(50 BYTE) 
, 発注件名 VARCHAR2(120 BYTE) 
, 初回見積依頼日 DATE 
, 見積依頼日 DATE 
, 発注日 DATE 
, 開始予定日 DATE 
, 入荷予定日 DATE 
, 検収予定日 DATE 
, 発注理由区分 VARCHAR2(3 BYTE) 
, 発注理由 VARCHAR2(30 BYTE) 
, 発注理由備考 VARCHAR2(120 BYTE) 
, 開示状況区分 VARCHAR2(3 BYTE) 
, 開示状況 VARCHAR2(30 BYTE) 
, 開示状況備考 VARCHAR2(120 BYTE) 
, 相見積状況区分 VARCHAR2(3 BYTE) 
, 相見積状況 VARCHAR2(30 BYTE) 
, 相見積状況備考 VARCHAR2(120 BYTE) 
, 選定理由区分 VARCHAR2(3 BYTE) 
, 選定理由 VARCHAR2(30 BYTE) 
, 選定理由備考 VARCHAR2(120 BYTE) 
, 発注金額 NUMBER(10, 0) 
, 手続き状態区分 VARCHAR2(3 BYTE) 
, 手続状態区分名 VARCHAR2(30 BYTE) 
, 小額 NUMBER(10, 0) 
, 特化 VARCHAR2(30 BYTE) 
, 見積区分 VARCHAR2(20 BYTE) 
, プロジェクト番号 VARCHAR2(20 BYTE) 
, プロジェクト名 VARCHAR2(120 BYTE) 
, CONSTRAINT PK_SUPPLYORDER PRIMARY KEY 
  (
    発注番号 
  , 発注版数 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_SUPPLYORDER ON FT_SUPPLYORDER (発注番号 ASC, 発注版数 ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
