CREATE TABLE FT_PLANORDER 
(
  Žó’Œv‰æ”Ô† VARCHAR2(10 BYTE) 
, Œ–¼ VARCHAR2(120 BYTE) 
, “¾ˆÓæ VARCHAR2(50 BYTE) 
, ƒ†[ƒU VARCHAR2(50 BYTE) 
, Žó’”Ô† VARCHAR2(10 BYTE) 
, Œ©Ï”Ô† VARCHAR2(10 BYTE) 
, ’•¶”Ô† VARCHAR2(10 BYTE) 
, Žè‘±ó‘Ô VARCHAR2(20 BYTE) 
, ”„ã—\‘ª NUMBER(10, 0) 
, Œ´‰¿—\‘ª NUMBER(10, 0) 
, Œ´‰¿—¦ NUMBER(1, 3) 
, ’•¶‹àŠzˆêŠ‡ NUMBER(10, 0) 
, Œ©ÏŒ´‰¿ˆêŠ‡ NUMBER(10, 0) 
, Œ´‰¿—¦ˆêŠ‡ NUMBER(1, 3) 
, ’•¶‹àŠzŒŽŠz NUMBER(10, 0) 
, Œ©ÏŒ´‰¿ŒŽŠz NUMBER(10, 0) 
, Œ´‰¿—¦ŒŽŠz NUMBER(1, 3) 
, ’•¶‹àŠz”NŠz NUMBER(10, 0) 
, Œ©ÏŒ´‰¿”NŠz NUMBER(10, 0) 
, Œ´‰¿—¦”NŠz NUMBER(1, 3) 
, ’•¶‹àŠzŽÀÑ NUMBER(10, 0) 
, Œ©ÏŒ´‰¿ŽÀÑ NUMBER(10, 0) 
, Œ´‰¿—¦ŽÀÑ NUMBER(1, 3) 
, Žó’—\’è“ú•t DATE 
, æs VARCHAR2(5 BYTE) 
, Žó’ƒ‰ƒ“ƒN VARCHAR2(3 BYTE) 
, Žó’’S“– VARCHAR2(50 BYTE) 
, ”„ã’S“– VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
