CREATE TABLE FT_PLANORDER 
(
  受注計画番号 VARCHAR2(10 BYTE) NOT NULL 
, 件名 VARCHAR2(120 BYTE) 
, 得意先 VARCHAR2(50 BYTE) 
, ユーザ VARCHAR2(50 BYTE) 
, 受注番号 VARCHAR2(10 BYTE) 
, 見積番号 VARCHAR2(10 BYTE) 
, 注文番号 VARCHAR2(10 BYTE) 
, 手続状態 VARCHAR2(20 BYTE) 
, 売上予測 NUMBER(10, 0) 
, 原価予測 NUMBER(10, 0) 
, 原価率 NUMBER(1, 3) 
, 注文金額一括 NUMBER(10, 0) 
, 見積原価一括 NUMBER(10, 0) 
, 原価率一括 NUMBER(1, 3) 
, 注文金額月額 NUMBER(10, 0) 
, 見積原価月額 NUMBER(10, 0) 
, 原価率月額 NUMBER(1, 3) 
, 注文金額年額 NUMBER(10, 0) 
, 見積原価年額 NUMBER(10, 0) 
, 原価率年額 NUMBER(1, 3) 
, 注文金額実績 NUMBER(10, 0) 
, 見積原価実績 NUMBER(10, 0) 
, 原価率実績 NUMBER(1, 3) 
, 受注予定日付 DATE 
, 先行 VARCHAR2(5 BYTE) 
, 受注ランク VARCHAR2(3 BYTE) 
, 受注担当 VARCHAR2(50 BYTE) 
, 売上担当 VARCHAR2(50 BYTE) 
, CONSTRAINT PK_PLANORDER PRIMARY KEY 
  (
    受注計画番号 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_PLANORDER ON FT_PLANORDER (受注計画番号 ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
